fix appdrawer import
this was causing the following error when opening the drawer:
Error: Could not find the correct Provider<DrawerStateInfo> above this AppDrawer Widget